[package]
name = "gomoku"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.95"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies.druid]
version = "0.8.3"
features = ["im"]

